### ISSUE TITLE
Behov for å referere til datasett som er input til tjeneste og som ikke er et dokumentasjonskrav

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/cpsv-ap-no#10]
I v.0.7 er det kun via cv:Evidence og derfra koples til datasett som brukes som input til en tjeneste. Det er behov for å kunne referere til data som brukes som input til en tjeneste og som ikke er dokumentasjonskrav. 

Løsningen kan være å føye til en optional duv:refersTo i klassen Tjeneste, 0..n, range dcat:Dataset.

**Comment by jimjyang** [comment]
Gjelder ikke bare klassen Tjeneste (cpsvno:Service) med subklassen Offentlig tjeneste (cpsv:PublicService) men også Tjenestekanal (cv:Channel)

**Comment by stigbd** [comment]
Sliter med å forstå behovet fullt ut: Kva for input er det vi tenker på her? 
duv:refersTo er jo _veldig_ generell og er "datasett-speak". Vi burde forsøke å bruke domene-språk, dvs egenskaper knytta til tjenester.
Forøvrig kunne det ha vore interessant å forstå overgangen frå Input til Evidence. Antagelegvis kan vi forstå intensjonen litt betre om vi forstår argumentasjonen der.

**Comment by jimjyang** [comment]
Det er nå i v.0.8 tatt med følgende forklaring under [Å knytte en (offentlig) tjeneste til et datasett og derfra til API, begrep og informasjonsmodell](https://informasjonsforvaltning.github.io/cpsv-ap-no/#KnytteTilDatasett): "Ut fra den engelske usage note til [Klassen Dokumentasjon (cv:Evidence)](https://informasjonsforvaltning.github.io/cpsv-ap-no/#Dokumentasjon), kan dokumentasjon (evidence) være en hvilken som helst ressurs som trengs for å utføre en (offentlig) tjeneste, også et utfylt søknadsskjema." 

Behovet regnes som dekket.

**Comment by jimjyang** [comment]
Lukkes, da behovet anses dekket.
