### ISSUE TITLE
har deltager i Deltagelse-diagram angitt som anbefalt -> bør være obligatorisk?

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/cpsv-ap-no#127]
Spec'en angir predikatet cv:hasParticipant som obligatorisk (og 1..1) mens diagrammet (vedlagt) viser at Aktør-klassen kun er anbefalt. Er det meningen?

![bilde](https://user-images.githubusercontent.com/108797958/212314601-4cf41cdc-8575-469c-878d-ec1b7e758f90.png)

**Comment by terjesyl** [comment]
Nevermind, tror jeg tolker spec'en feil. Issuet kan sikkert lukkes.

**Comment by jimjyang** [comment]
Deltager (klassen Aktør) trenger ikke å være obligatorisk. Jeg lukker issuet.
