### ISSUE TITLE
[ontology] Feil tittel og beskrivelse i ontologi

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/cpsv-ap-no#13]
cpsvno er eit vokabular og ikkje ein applikasjonsprofil. Derfor må vi endre frå `cpsv-ap-no` til `cpsvno` i tittel og beskrivelse på vokabularet. cpsv-ap-no (applikasjonsprofilen) bruker vokabularet, så derfor er dette to ting.

**Comment by jimjyang** [comment]
Vi har gått vekk fra denne publiseringsløsningen og problemstillingen dermed uaktuell nå. Lukkes.
