### ISSUE TITLE
Kontrollert vokabular på hendelser

### ISSUE THREAD

**Issue by Tormodvar** [Informasjonsforvaltning/cpsv-ap-no#15]
Det er svært vanskelig å enes om et felles vokabular på tvers av ulike sektorer, virksomheter og organisasjoner. Det er nok også derfor dette tar tid å lande. Min anbefaling er at man forstår problemet ut fra Domene Drevet Design og tillegger dette en styringsmodell (Governance). De ulike domenene må defineres sentralt (eks hos DigDir) og man kan ta utgangspunkt i sektorene i det offentlige, eller en finere granulering. Hvert domene tilordnes et styrende organ som bestemmer hendelser innen sitt domene. De som skal konsumere hendelsen må forstå hendelsen ut i fra konteksten i domenet den oppstår i. Men det er bare slik det er. Et kontrollert vokabular på hendelser vil med dette forslaget få en hierarkisk oppbygging. Eksempelvis vil hendelser for Helse ha samme begrep som innen Forsvaret, men de vil ha ulik betydning ut i fra sin kontekst (domene).

**Comment by jimjyang** [comment]
Takk, @Tormodvar! Vi tar med oss dette innspillet videre til arbeidet med selve vokabularene.

**Comment by jimjyang** [comment]
Saken lukkes
