### ISSUE TITLE
Publisering av cpsvno - en liten bug

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/cpsv-ap-no#5]
Det blir en "/" for mye (foran "#") i URLen. 

https://data.norge.no/vocabulary/cpsvno#ruleForDisclosure gir nå https://data.norge.no/vocabulary/cpsvno/#ruleForDisclosure

**Comment by stigbd** [comment]
Eg greier hverken å finne referanse til at "slash hash" er ulovlig. Så dette burde fungere.Issuet er heller at  https://data.norge.no/vocabulary/cpsvno/#ruleForDisclosure ikkje fungerer.

**Comment by jimjyang** [comment]
Vi har hittil sagt at navnerommet = https://data.norge.no/vocabulary/cpsvno# (ikke https://data.norge.no/vocabulary/cpsvno/#), er det da ikke en slash for mye foran hash når URLen blir https://data.norge.no/vocabulary/cpsvno/#ruleForDisclosure?

**Comment by jimjyang** [comment]
Vi har gått vekk fra denne publiseringsløsningen, problemstilingen dermed uaktuell nå. Lukkes.
