### ISSUE TITLE
Vi bør bruke rdf:langString istedenfor rdfs:Literal ...

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/cpsv-ap-no#81]
... der det skal være language-tagged string values, f.eks. dct:title, dct:description, ...

**Comment by stigbd** [comment]
Kva er motiviasjonen for dette?
dct:title har feks range rdfs:Literal, så eg synes det bør vere svært gode grunnar til å avvike frå dette.
Ref https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/title/

**Comment by stigbd** [comment]
Ser forøvrig at [rdf:langString](https://www.w3.org/TR/rdf-schema/#ch_langstring) er sub-klasse av rdfs:Literal

**Comment by jimjyang** [comment]
Hensyntatt i kommenteringsversjonen
