### ISSUE TITLE
Feil i menystrukturen på html-siden for klassen Dokumentasjon

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/cpsv-ap-no#96]
Egenskapen Dokumentasjon - understøtter krav ligger på samme nivå som menyoverskriftene obligatorisk, anbefalte og valgfri egenskaper for klassen Dokumentasjon. Skal ligge under menyoverskriften valgfri.
I tillegg ligger egenskapen Dokumentasjon - utsteder under denne igjen.

![image](https://user-images.githubusercontent.com/43232700/194076766-8704d162-8907-4d4b-9ece-c8775f305f94.png)

**Comment by jimjyang** [comment]
Rettes
