### ISSUE TITLE
Klassen Organisasjon bør også inneholde egenskapen hjemmeside

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/cpsv-ap-no#97]
Vi har lagt til egenskapen «hjemmeside» på klassen Offentlig organisasjon. Dette bør også legges til på klassen Organisasjon som er eier av tjenstene som ikke er offentlige. Burde egenskapen også legges på superklassen Aktør?

**Comment by jimjyang** [comment]
Vi legger til hjemmeside for Organisasjon, men foreløpig ikke for Aktør (ifm. tjenesteyting, bør en tjeneste eies/utføres av en Aktør som er en Organisasjon).
