### ISSUE TITLE
Burde egenskapene «Foretrukket navn» og «Dekningsområde» også finnes i klassen Organisasjon?

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/cpsv-ap-no#98]
Offentlig organisasjon, som er subklasse av Organisasjon, har egenskapene «Foretrukket navn» og «Dekningsområde». Burde ikke disse egenskapene også finnes i superklassen Organisasjon?

**Comment by jimjyang** [comment]
Vi føyer til "Foretrukket nav" og Dekningsområde i klassen Organisasjon.
